#!/bin/bash
alias gd="clear && git diff"
alias gdc="clear && git diff --cached"
alias gap="clear && git add -p"
alias gs="git status"
alias gsu="git status -u"
alias gsi="git status -u --ignored"
alias gc="git commit"
alias gcm="git commit -m"
alias gpf="git pull -ff"

alias ap="aptitude"
alias sau="sudo aptitude update"
alias asus="sudo aptitude safe-upgrade -sy"
alias asuy="sudo aptitude safe-upgrade -y"
alias ack="ack-grep"
