#!/bin/bash
alias gd="clear && git diff"
alias gdc="clear && git diff --cached"
alias gap="clear && git add -p"
alias gs="git status"
alias gsu="git status -u"
alias gsi="git status -u --ignored"
alias gc="git commit"
alias gcm="git commit -m"
alias gpf="git pull --ff"

alias ap="aptitude"
alias sau="sudo aptitude update"
alias asus="sudo aptitude safe-upgrade -sy"
alias asuy="sudo aptitude safe-upgrade -y"
alias ack="ack-grep"
alias vpn="xdg-open ~/Desktop/vpn-parkway.desktop"
alias deletertidb="ant init.cleanup.db -Ddev.cleanup.db=True"
alias R=". rti"
alias apu="aptitude search ~U -F \"%c%S%M %a %p %v %V %t %r %d\""
alias gbn="git branch --no-merged"
alias stt=". set_term_title"
alias gffs="git flow feature start"
alias gfff="git flow feature finish"
alias gff="git flow feature"
