#!/bin/bash
tmux start-server\; has-session -t tcfecru 2>/dev/null

if [ "$?" -eq 1 ]; then
  cd /home/paulf/teamcity-fecru

  # Run pre command.
  

  # Create the session and the first window.
  TMUX= tmux new-session -d -s tcfecru -n VIM


  # Create other windows.
  tmux new-window -c /home/paulf/teamcity-fecru -t tcfecru:2 -n SHELL


  # Window "VIM"
  
  tmux send-keys -t tcfecru:1.1 '' C-m
  tmux send-keys -t tcfecru:1.1 vim C-m

  tmux splitw -t tcfecru:1
  tmux select-layout -t tcfecru:1 main-vertical
  
  tmux send-keys -t tcfecru:1.2 '' C-m
  tmux send-keys -t tcfecru:1.2 top C-m

  tmux select-layout -t tcfecru:1 main-vertical

  tmux select-pane -t tcfecru:1.1

  # Window "SHELL"
  
  tmux send-keys -t tcfecru:2 top C-m

  tmux select-window -t 1
fi

if [ -z "$TMUX" ]; then
  tmux -u attach-session -t tcfecru
else
  tmux -u switch-client -t tcfecru
fi
